In [1]:
import torch
import numpy as np

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Initialize a (2 x 3) tensor
tensor = torch.tensor([[1, 2, 3],
                     [4, 5, 6]],
                     dtype=torch.float32, device=device, requires_grad=True)

In [3]:
# Print tensor information
print(f'General information:\n{tensor}')
print(f'Data type: {tensor.dtype}')
print(f'Device: {tensor.device}')
print(f'Shape: {tensor.shape}') # tensor.size()
print(f'Requires gradient (trainable): {tensor.requires_grad}')

General information:
tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
Data type: torch.float32
Device: cpu
Shape: torch.Size([2, 3])
Requires gradient (trainable): True


In [4]:
# Tensor initialization methods 1
x1 = torch.empty(size=(3, 3)) # uninitialized data
x2 = torch.zeros((3, 3)) # values of 0
x3 = torch.rand((3, 3)) # values from uniform distribution in interval [0, 1)
x4 = torch.ones((3, 3)) # values of 1
x5 = torch.eye(5, 5) # identity matrix (I = eye)

tensors = [x1, x2, x3, x4, x5]

for i, t in enumerate(tensors, start=1):
    print(f'x{i}:\n{t}')

x1:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
x2:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
x3:
tensor([[0.6163, 0.5538, 0.8472],
        [0.7847, 0.1056, 0.8945],
        [0.2283, 0.4600, 0.8859]])
x4:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
x5:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [5]:
# Tensor initialization methods 2
x6 = torch.arange(start=0, end=5, step=1)
x7 = torch.arange(11)
x8 = torch.linspace(start=0.1, end=1, steps=10) # [0.1, 0.2, ..., 1]
x9 = torch.empty(size=(1, 5)).normal_(mean=0, std=1) # normally distributed (mean=0, std=1)
x10 = torch.empty(size=(1, 5)).uniform_(0, 1) # values from a uniform distribution (low=0, high=1)
x11 = torch.diag(torch.ones(3)) # diagonal matrix (3 x 3)

tensors = [x6, x7, x8, x9, x10, x11]

for i, t in enumerate(tensors, start=6):
    print(f'x{i}:\n{t}')

x6:
tensor([0, 1, 2, 3, 4])
x7:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
x8:
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
x9:
tensor([[ 0.5717,  0.2616, -1.3283, -0.5141,  1.2439]])
x10:
tensor([[0.8847, 0.3541, 0.2201, 0.0490, 0.5548]])
x11:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [6]:
# Manipulate tensor types
# int64, float32 very important, used super often

tensor = torch.arange(4) # default: int64

print(f'Boolean (1 if non-zero): {tensor.bool()}')
print(f'int16: {tensor.short()}')
print(f'int64: {tensor.long()}')
print(f'float16: {tensor.half()}')
print(f'float32: {tensor.float()}')
print(f'float64: {tensor.double()}')

Boolean (1 if non-zero): tensor([False,  True,  True,  True])
int16: tensor([0, 1, 2, 3], dtype=torch.int16)
int64: tensor([0, 1, 2, 3])
float16: tensor([0., 1., 2., 3.], dtype=torch.float16)
float32: tensor([0., 1., 2., 3.])
float64: tensor([0., 1., 2., 3.], dtype=torch.float64)


In [7]:
# Array to tensor conversion and vice-versa
np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
np_array_re = tensor.numpy() # same as np_array (perhaps with numerical round-offs)

print(np_array, '\n')
print(tensor, '\n')
print(np_array_re, '\n')

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64) 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

