In [1]:
import torch

In [2]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

In [3]:
# Addition
z1 = torch.empty(3) # [0, 0, 0]
torch.add(x, y, out=z1)

z2 = torch.add(x, y)
z3 = x + y

print(z1, z2, z3)

tensor([10., 10., 10.]) tensor([10, 10, 10]) tensor([10, 10, 10])


In [4]:
# Subtraction
z1 = x - y

# Division (element wise division if of equal shape)
z2 = torch.true_divide(x, y)

# Multiplication (element wise)
z3 = torch.mul(x, y)
z4 = x * y

print(z1, z2)
print(z3, z4)

tensor([-8, -6, -4]) tensor([0.1111, 0.2500, 0.4286])
tensor([ 9, 16, 21]) tensor([ 9, 16, 21])


In [5]:
# Inplace operations
t = torch.zeros(3)
t1 = t + x # not an inplace operation
print(t, t1)

t += x # inplace
print(t)

t2 = t.add_(x) # whenever followed by _ mutate the tensor inplace
print(t, t2)

tensor([0., 0., 0.]) tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([2., 4., 6.]) tensor([2., 4., 6.])


In [6]:
# Exponentiation (element wise if vector or matrices)
z1 = x.pow(2)
z2 = x**2

print(z1, z2)

tensor([1, 4, 9]) tensor([1, 4, 9])


In [7]:
# Simple comparison
z1 = x > 0
z2 = x < 0

print(z1, z2)

tensor([True, True, True]) tensor([False, False, False])


In [8]:
# Matrix multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2) # if of equal shape
x4 = x1.mm(x2)
x5 = x1 @ x2 # same as mm()

print(x3)
print(x4)
print(x5)

tensor([[1.4376, 1.7676, 1.2091],
        [0.6480, 1.7530, 1.3276]])
tensor([[1.4376, 1.7676, 1.2091],
        [0.6480, 1.7530, 1.3276]])
tensor([[1.4376, 1.7676, 1.2091],
        [0.6480, 1.7530, 1.3276]])


In [9]:
x6 = torch.matmul(x1, x2) # broadcasting (works for matrices with different shapes)

print(x6)

tensor([[1.4376, 1.7676, 1.2091],
        [0.6480, 1.7530, 1.3276]])


In [10]:
# Matrix exponentiation
t = torch.rand(5, 5)
t1 = t.matrix_power(3)

print(t)
print(t1)

tensor([[0.3598, 0.7775, 0.1767, 0.4434, 0.0284],
        [0.3064, 0.0081, 0.1160, 0.3029, 0.6937],
        [0.0026, 0.8742, 0.7211, 0.7371, 0.4737],
        [0.5187, 0.9970, 0.9748, 0.9327, 0.4236],
        [0.2551, 0.4458, 0.6192, 0.0536, 0.2336]])
tensor([[1.1931, 2.4236, 2.1672, 2.0000, 1.5762],
        [0.8282, 1.8125, 1.5645, 1.6491, 1.3957],
        [1.9017, 4.1596, 3.8198, 3.5098, 2.8556],
        [2.6622, 5.5617, 5.0879, 4.8261, 3.9657],
        [0.9654, 1.9722, 1.8675, 1.7115, 1.4699]])


In [11]:
# Dot product
z1 = torch.dot(x, y)
z2 = x @ y # also used to compute the dot product of two vectors

print(z1, z2)

tensor(46) tensor(46)


In [12]:
# Batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

t1 = torch.rand((batch, n, m))
t2 = torch.rand((batch, m, p))

out_bmm = torch.bmm(t1, t2) # (b x n x p)
print(out_bmm.shape)

torch.Size([32, 10, 30])


In [13]:
# Example of broadcasting
x1 = torch.rand((5, 5))
x2 = torch.ones((1, 5))

z1 = x1 - x2
z2 = x1**x2

print(z1, z1.shape)
print(z2, z2.shape)

tensor([[-0.6354, -0.4328, -0.1144, -0.1992, -0.9091],
        [-0.1384, -0.5422, -0.9966, -0.1182, -0.4581],
        [-0.1832, -0.2330, -0.2424, -0.2583, -0.0949],
        [-0.3543, -0.4698, -0.6999, -0.5083, -0.1193],
        [-0.9517, -0.2098, -0.7045, -0.8122, -0.8450]]) torch.Size([5, 5])
tensor([[0.3646, 0.5672, 0.8856, 0.8008, 0.0909],
        [0.8616, 0.4578, 0.0034, 0.8818, 0.5419],
        [0.8168, 0.7670, 0.7576, 0.7417, 0.9051],
        [0.6457, 0.5302, 0.3001, 0.4917, 0.8807],
        [0.0483, 0.7902, 0.2955, 0.1878, 0.1550]]) torch.Size([5, 5])


In [14]:
# Other useful tensor operations
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

sum_x = torch.sum(x, dim=0) # sum of x across dim=0 (the only dim in this case)
values_max, indices_max = torch.max(x, dim=0) # x.max(dim=0)
values_min, indices_min = torch.min(x, dim=0) # x.min(dim=0)
abs_x = torch.abs(x) # abs() applied to every element
mean_x = torch.mean(x.float(), dim=0) # mean requires x to be a float
eq_xy = torch.eq(x, y) # element wise comparison
sorted_y, indices_y = torch.sort(y, dim=0, descending=False)

print(sum_x)
print(values_max, indices_max)
print(values_min, indices_min)
print(abs_x)
print(mean_x)
print(eq_xy)
print(sorted_y, indices_y)

tensor(6)
tensor(3) tensor(2)
tensor(1) tensor(0)
tensor([1, 2, 3])
tensor(2.)
tensor([False, False, False])
tensor([7, 8, 9]) tensor([2, 1, 0])


In [15]:
argmax_x = torch.argmax(x, dim=0) # index of the maximum value
argmin_x = torch.argmin(x, dim=0) # index of the minimum value

clamp_x = torch.clamp(x, min=0) # all values < 0 set to 0 and values > 0 unchanged (ReLU)
clamp_y = torch.clamp(y, min=0, max=7) # values greater than 7 also clamped

print(argmax_x)
print(argmin_x)
print(clamp_x)
print(clamp_y)

tensor(2)
tensor(0)
tensor([1, 2, 3])
tensor([7, 7, 7])


In [16]:
x = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool) # boolean values
z1 = torch.any(x) # x.any()
z2 = torch.all(x) # x.all()

print(z1, z2)

tensor(True) tensor(False)
