In [1]:
import torch

In [2]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x.shape)
x[:5]

torch.Size([10, 25])


tensor([[0.4540, 0.2821, 0.1010, 0.8375, 0.7844, 0.0284, 0.2104, 0.4453, 0.3774,
         0.9091, 0.7464, 0.3854, 0.9051, 0.6324, 0.3575, 0.2062, 0.0077, 0.2429,
         0.1533, 0.2243, 0.9263, 0.5762, 0.7479, 0.6345, 0.1683],
        [0.4056, 0.5177, 0.1345, 0.3542, 0.0441, 0.3875, 0.1458, 0.1837, 0.6646,
         0.1358, 0.5116, 0.4353, 0.1721, 0.0531, 0.5879, 0.7717, 0.7622, 0.5077,
         0.2199, 0.4236, 0.7113, 0.1732, 0.2262, 0.0231, 0.2821],
        [0.9833, 0.7962, 0.4258, 0.3246, 0.7161, 0.5988, 0.6729, 0.1404, 0.1018,
         0.8267, 0.4542, 0.9009, 0.9212, 0.0591, 0.5295, 0.0370, 0.4000, 0.5880,
         0.0804, 0.2776, 0.9288, 0.8411, 0.7544, 0.3138, 0.4282],
        [0.4726, 0.6471, 0.1308, 0.4493, 0.9565, 0.4617, 0.9753, 0.8355, 0.2185,
         0.7193, 0.3766, 0.4075, 0.2561, 0.6352, 0.5055, 0.0932, 0.3405, 0.9848,
         0.5676, 0.2224, 0.9844, 0.9365, 0.5896, 0.2356, 0.4139],
        [0.9386, 0.4624, 0.6259, 0.1183, 0.2324, 0.8121, 0.2299, 0.2306, 0.2611,
       

In [3]:
# Get all features for the first example from the batch
print(x[0].shape) # x[0, :].shape

# Get the first feature for all examples
print(x[:, 0].shape)

# Access the first ten features of the third example
print(x[2, :10].shape)

# Assign certain elements
print(x[0, 0])
x[0, 0] = 100
print(x[0, 0])

torch.Size([25])
torch.Size([10])
torch.Size([10])
tensor(0.4540)
tensor(100.)


In [4]:
# Fancy indexing
x = torch.arange(10)
indices = [2, 5, 8]

print(x)
print(x[indices])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([2, 5, 8])


In [5]:
x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])

print(x)
print(x[rows, cols]) # second row fifth column (1, 4), first row first column (0, 0)

tensor([[0.2877, 0.5348, 0.8790, 0.2629, 0.1553],
        [0.2548, 0.1270, 0.1357, 0.2097, 0.9493],
        [0.1491, 0.8774, 0.8622, 0.6382, 0.9651]])
tensor([0.9493, 0.2877])


In [6]:
# More advanced indexing
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])
print(x[x.remainder(2) == 0])

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [7]:
# Useful operations for indexing
t1 = torch.where(x > 5, x, x * 2) # all values greater than 5 yield x, else x*2
t2 = torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique()

print(t1)
print(t2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])


In [8]:
x = torch.arange(10)
y = torch.rand((5, 5, 5)) # (5 x 5 x 5)

print(x.ndimension(), y.ndimension()) # the number of dimensions
print(x.numel(), y.numel()) # the number of elements

1 3
10 125
